[build-system]
backend-path = ['']
build-backend = 'pypi_compatible_build'
requires = ['setuptools>=77', 'setuptools_scm']

[project]
description = ''
name = 'whodoneit'
readme = 'README.md'
requires-python = '>=3.12'
dynamic = ['version']

dependencies = [
    
    'allowedflare',
    
    'django-plugin-field-day @ git+https://github.com/biobuddies/django-plugin-field-day.git',
    
    'gunicorn',
    
]

[project.optional-dependencies]
build = [
    'setuptools',
]
pre-commit = [
    'actionlint-py',
    'basedpyright',
    'cookiecutter',
    'django-upgrade',
    'djlint>=1.45.0',
    'hadolint-py @ git+https://github.com/AleksaC/hadolint-py.git',
    'pre-commit-hooks',
    'pyrefly',
    'ruff',
    'shellcheck-py',
    'shfmt-py',
    'styleforce',
    'typos',
    'validate-pyproject[all]',
    'yamllint',
]
test = [
    'pytest',
    'pytest-cov',
    'pytest-django',
]

[project.urls]
source = 'https://github.com/biobuddies/whodoneit'

[tool.coverage.run]
source_pkgs = ['whodoneit']

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = 'config.settings'
norecursedirs = ['.venv', 'node_modules', '{{cookiecutter.dot}}']

[tool.setuptools]
py-modules = ['whodoneit']

[tool.setuptools_scm]

[tool.basedpyright]
extends = '.biobuddies/basedpyright.toml'

[tool.djlint]
close_void_tags = true
format_attribute_template_tags = true
indent = 4
max_attribute_length = 100
max_blank_lines = 1
max_line_length = 100
no_entity_formatting = true
quote_style = 'single'

[tool.ruff]
extend = '.biobuddies/ruff.toml'

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
